/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) metabolic_energy_models_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[4] = {1, 1, 0, 0};
static const casadi_int casadi_s2[59] = {6, 12, 0, 5, 8, 12, 16, 20, 23, 28, 33, 36, 39, 40, 44, 0, 1, 2, 3, 5, 0, 3, 5, 0, 2, 3, 5, 0, 3, 4, 5, 0, 3, 4, 5, 0, 3, 5, 0, 1, 2, 3, 5, 0, 1, 2, 3, 5, 0, 3, 5, 0, 3, 5, 5, 0, 3, 4, 5};

/* f_getMetabolicEnergySmooth2004all:(exc_SX,act_SX,lMtilde_SX,vM_SX,FT_SX,FT_SX,musclemass_SX,pctst_SX,Fiso_SX,FMo_SX,modelmass_SX,b_SX)->(Edot,Adot,Mdot,Sdot,Wdot,Edot+basal) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[6]? arg[6][0] : 0;
  a1=40.;
  a2=arg[7]? arg[7][0] : 0;
  a3=1.5707963267948966e+000;
  a4=arg[0]? arg[0][0] : 0;
  a5=(a3*a4);
  a5=sin(a5);
  a5=(a2*a5);
  a1=(a1*a5);
  a6=133.;
  a7=1.;
  a2=(a7-a2);
  a3=(a3*a4);
  a3=cos(a3);
  a3=(a7-a3);
  a2=(a2*a3);
  a6=(a6*a2);
  a1=(a1+a6);
  a1=(a0*a1);
  a6=arg[2]? arg[2][0] : 0;
  a6=(a0*a6);
  a3=74.;
  a3=(a3*a5);
  a5=111.;
  a5=(a5*a2);
  a3=(a3+a5);
  a6=(a6*a3);
  a3=(a1+a6);
  a5=1.6000000000000000e-001;
  a2=arg[1]? arg[1][0] : 0;
  a4=arg[8]? arg[8][0] : 0;
  a2=(a2*a4);
  a4=arg[9]? arg[9][0] : 0;
  a2=(a2*a4);
  a5=(a5*a2);
  a2=1.7999999999999999e-001;
  a4=arg[4]? arg[4][0] : 0;
  a8=arg[5]? arg[5][0] : 0;
  a8=(a4+a8);
  a2=(a2*a8);
  a5=(a5+a2);
  a2=1.5700000000000000e-001;
  a2=(a2*a8);
  a2=(a2-a5);
  a8=5.0000000000000000e-001;
  a9=arg[11]? arg[11][0] : 0;
  a10=arg[3]? arg[3][0] : 0;
  a11=(a9*a10);
  a11=tanh(a11);
  a11=(a8*a11);
  a11=(a8+a11);
  a2=(a2*a11);
  a5=(a5+a2);
  a5=(a5*a10);
  a2=(a1+a6);
  a2=(a2-a5);
  a4=(a4*a10);
  a11=(a7-a11);
  a4=(a4*a11);
  a2=(a2-a4);
  a11=(a9*a2);
  a11=(-a11);
  a11=tanh(a11);
  a11=(a8*a11);
  a11=(a8+a11);
  a2=(a2*a11);
  a5=(a5+a2);
  a3=(a3-a5);
  a3=(a3/a0);
  a2=(a7-a3);
  a7=(a7-a3);
  a9=(a9*a7);
  a9=tanh(a9);
  a9=(a8*a9);
  a8=(a8+a9);
  a2=(a2*a8);
  a3=(a3+a2);
  a3=(a3*a0);
  a3=(a3-a4);
  if (res[0]!=0) res[0][0]=a3;
  if (res[1]!=0) res[1][0]=a1;
  if (res[2]!=0) res[2][0]=a6;
  a5=(-a5);
  if (res[3]!=0) res[3][0]=a5;
  a4=(-a4);
  if (res[4]!=0) res[4][0]=a4;
  a4=1.2000000000000000e+000;
  a5=arg[10]? arg[10][0] : 0;
  a4=(a4*a5);
  a4=(a4+a3);
  if (res[5]!=0) res[5][0]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_getMetabolicEnergySmooth2004all(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_getMetabolicEnergySmooth2004all_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_getMetabolicEnergySmooth2004all_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_getMetabolicEnergySmooth2004all_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_getMetabolicEnergySmooth2004all_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_getMetabolicEnergySmooth2004all_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_getMetabolicEnergySmooth2004all_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_getMetabolicEnergySmooth2004all_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_getMetabolicEnergySmooth2004all_n_in(void) { return 12;}

CASADI_SYMBOL_EXPORT casadi_int f_getMetabolicEnergySmooth2004all_n_out(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_real f_getMetabolicEnergySmooth2004all_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_getMetabolicEnergySmooth2004all_name_in(casadi_int i){
  switch (i) {
    case 0: return "exc_SX";
    case 1: return "act_SX";
    case 2: return "lMtilde_SX";
    case 3: return "vM_SX";
    case 4: return "FT_SX";
    case 5: return "FT_SX";
    case 6: return "musclemass_SX";
    case 7: return "pctst_SX";
    case 8: return "Fiso_SX";
    case 9: return "FMo_SX";
    case 10: return "modelmass_SX";
    case 11: return "b_SX";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_getMetabolicEnergySmooth2004all_name_out(casadi_int i){
  switch (i) {
    case 0: return "Edot";
    case 1: return "Adot";
    case 2: return "Mdot";
    case 3: return "Sdot";
    case 4: return "Wdot";
    case 5: return "Edot+basal";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_getMetabolicEnergySmooth2004all_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_getMetabolicEnergySmooth2004all_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_getMetabolicEnergySmooth2004all_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jac_f_getMetabolicEnergySmooth2004all:(exc_SX,act_SX,lMtilde_SX,vM_SX,FT_SX,FT_SX,musclemass_SX,pctst_SX,Fiso_SX,FMo_SX,modelmass_SX,b_SX,out_Edot[1x1,0nz],out_Adot[1x1,0nz],out_Mdot[1x1,0nz],out_Sdot[1x1,0nz],out_Wdot[1x1,0nz],out_Edot+basal[1x1,0nz])->(jac[6x12,44nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a8, a9;
  a0=1.5707963267948966e+000;
  a1=arg[0]? arg[0][0] : 0;
  a2=(a0*a1);
  a3=sin(a2);
  a4=1.;
  a5=arg[7]? arg[7][0] : 0;
  a6=(a4-a5);
  a7=111.;
  a8=arg[6]? arg[6][0] : 0;
  a9=arg[2]? arg[2][0] : 0;
  a10=(a8*a9);
  a11=arg[11]? arg[11][0] : 0;
  a12=40.;
  a1=(a0*a1);
  a13=sin(a1);
  a14=(a5*a13);
  a15=(a12*a14);
  a16=133.;
  a2=cos(a2);
  a2=(a4-a2);
  a17=(a6*a2);
  a18=(a16*a17);
  a15=(a15+a18);
  a18=(a8*a15);
  a19=74.;
  a14=(a19*a14);
  a17=(a7*a17);
  a14=(a14+a17);
  a17=(a10*a14);
  a20=(a18+a17);
  a21=1.6000000000000000e-001;
  a22=arg[1]? arg[1][0] : 0;
  a23=arg[8]? arg[8][0] : 0;
  a24=(a22*a23);
  a25=arg[9]? arg[9][0] : 0;
  a26=(a24*a25);
  a26=(a21*a26);
  a27=1.7999999999999999e-001;
  a28=arg[4]? arg[4][0] : 0;
  a29=arg[5]? arg[5][0] : 0;
  a29=(a28+a29);
  a30=(a27*a29);
  a26=(a26+a30);
  a30=1.5700000000000000e-001;
  a29=(a30*a29);
  a29=(a29-a26);
  a31=5.0000000000000000e-001;
  a32=arg[3]? arg[3][0] : 0;
  a33=(a11*a32);
  a33=tanh(a33);
  a34=(a31*a33);
  a34=(a31+a34);
  a35=(a29*a34);
  a26=(a26+a35);
  a35=(a26*a32);
  a20=(a20-a35);
  a36=(a28*a32);
  a37=(a4-a34);
  a38=(a36*a37);
  a20=(a20-a38);
  a38=(a11*a20);
  a38=(-a38);
  a38=tanh(a38);
  a39=casadi_sq(a38);
  a39=(a4-a39);
  a18=(a18+a17);
  a38=(a31*a38);
  a38=(a31+a38);
  a17=(a20*a38);
  a35=(a35+a17);
  a18=(a18-a35);
  a18=(a18/a8);
  a35=(a4-a18);
  a17=(a11*a35);
  a17=tanh(a17);
  a40=casadi_sq(a17);
  a40=(a4-a40);
  a41=(a4-a18);
  a42=(a41*a8);
  a42=(a31*a42);
  a42=(a40*a42);
  a43=(a11*a42);
  a43=(a8-a43);
  a17=(a31*a17);
  a17=(a31+a17);
  a44=(a17*a8);
  a43=(a43-a44);
  a44=(a43/a8);
  a45=(a20*a44);
  a45=(a31*a45);
  a45=(a39*a45);
  a46=(a11*a45);
  a47=(a38*a44);
  a46=(a46-a47);
  a47=(a46+a44);
  a48=(a10*a47);
  a49=(a7*a48);
  a50=(a46+a44);
  a51=(a8*a50);
  a52=(a16*a51);
  a49=(a49+a52);
  a52=(a6*a49);
  a52=(a3*a52);
  a52=(a0*a52);
  a1=cos(a1);
  a48=(a19*a48);
  a51=(a12*a51);
  a48=(a48+a51);
  a51=(a5*a48);
  a51=(a1*a51);
  a51=(a0*a51);
  a52=(a52+a51);
  if (res[0]!=0) res[0][0]=a52;
  a52=(a16*a8);
  a51=(a6*a52);
  a51=(a3*a51);
  a51=(a0*a51);
  a53=(a12*a8);
  a54=(a5*a53);
  a54=(a1*a54);
  a54=(a0*a54);
  a51=(a51+a54);
  if (res[0]!=0) res[0][1]=a51;
  a51=(a7*a10);
  a54=(a6*a51);
  a54=(a3*a54);
  a54=(a0*a54);
  a55=(a19*a10);
  a56=(a5*a55);
  a56=(a1*a56);
  a56=(a0*a56);
  a54=(a54+a56);
  if (res[0]!=0) res[0][2]=a54;
  a54=(a31*a20);
  a54=(a39*a54);
  a56=(a11*a54);
  a56=(a56-a38);
  a57=(a10*a56);
  a58=(a7*a57);
  a59=(a8*a56);
  a60=(a16*a59);
  a58=(a58+a60);
  a60=(a6*a58);
  a60=(a3*a60);
  a60=(a0*a60);
  a57=(a19*a57);
  a59=(a12*a59);
  a57=(a57+a59);
  a59=(a5*a57);
  a59=(a1*a59);
  a59=(a0*a59);
  a60=(a60+a59);
  if (res[0]!=0) res[0][3]=a60;
  a60=(a41*a8);
  a60=(a31*a60);
  a40=(a40*a60);
  a60=(a11*a40);
  a60=(a8-a60);
  a59=(a17*a8);
  a60=(a60-a59);
  a59=(a60/a8);
  a61=(a20*a59);
  a61=(a31*a61);
  a39=(a39*a61);
  a61=(a11*a39);
  a38=(a38*a59);
  a61=(a61-a38);
  a38=(a61+a59);
  a10=(a10*a38);
  a7=(a7*a10);
  a62=(a61+a59);
  a63=(a8*a62);
  a16=(a16*a63);
  a7=(a7+a16);
  a6=(a6*a7);
  a3=(a3*a6);
  a3=(a0*a3);
  a19=(a19*a10);
  a12=(a12*a63);
  a19=(a19+a12);
  a5=(a5*a19);
  a1=(a1*a5);
  a0=(a0*a1);
  a3=(a3+a0);
  if (res[0]!=0) res[0][4]=a3;
  a44=(a44+a46);
  a3=(a32*a44);
  a0=(a34*a3);
  a1=(a0-a3);
  a5=(a21*a1);
  a12=(a25*a5);
  a63=(a23*a12);
  if (res[0]!=0) res[0][5]=a63;
  a63=-1.;
  a10=(a63-a56);
  a6=(a32*a10);
  a16=(a34*a6);
  a64=(a6-a16);
  a65=(a21*a64);
  a66=(a25*a65);
  a67=(a23*a66);
  if (res[0]!=0) res[0][6]=a67;
  a59=(a59+a61);
  a67=(a32*a59);
  a34=(a34*a67);
  a68=(a34-a67);
  a21=(a21*a68);
  a25=(a25*a21);
  a23=(a23*a25);
  if (res[0]!=0) res[0][7]=a23;
  a47=(a14*a47);
  a23=(a8*a47);
  if (res[0]!=0) res[0][8]=a23;
  a23=(a8*a14);
  if (res[0]!=0) res[0][9]=a23;
  a23=(a14*a56);
  a69=(a8*a23);
  if (res[0]!=0) res[0][10]=a69;
  a38=(a14*a38);
  a69=(a8*a38);
  if (res[0]!=0) res[0][11]=a69;
  a46=(a63-a46);
  a69=(a37*a46);
  a70=(a28*a69);
  a44=(a26*a44);
  a70=(a70-a44);
  a33=casadi_sq(a33);
  a4=(a4-a33);
  a46=(a36*a46);
  a3=(a29*a3);
  a46=(a46+a3);
  a46=(a31*a46);
  a46=(a4*a46);
  a3=(a11*a46);
  a70=(a70-a3);
  if (res[0]!=0) res[0][12]=a70;
  a10=(a26*a10);
  a70=(a37*a56);
  a3=(a28*a70);
  a10=(a10-a3);
  a3=(a36*a56);
  a6=(a29*a6);
  a3=(a3+a6);
  a3=(a31*a3);
  a3=(a4*a3);
  a6=(a11*a3);
  a10=(a10+a6);
  if (res[0]!=0) res[0][13]=a10;
  a10=(a31*a36);
  a10=(a4*a10);
  a6=(a11*a10);
  a33=(a28*a37);
  a6=(a6-a33);
  if (res[0]!=0) res[0][14]=a6;
  a63=(a63-a61);
  a61=(a37*a63);
  a28=(a28*a61);
  a26=(a26*a59);
  a28=(a28-a26);
  a36=(a36*a63);
  a29=(a29*a67);
  a36=(a36+a29);
  a31=(a31*a36);
  a4=(a4*a31);
  a11=(a11*a4);
  a28=(a28-a11);
  if (res[0]!=0) res[0][15]=a28;
  a69=(a32*a69);
  a1=(a27*a1);
  a0=(a30*a0);
  a1=(a1-a0);
  a69=(a69+a1);
  if (res[0]!=0) res[0][16]=a69;
  a16=(a30*a16);
  a64=(a27*a64);
  a16=(a16+a64);
  a70=(a32*a70);
  a70=(a16-a70);
  if (res[0]!=0) res[0][17]=a70;
  a37=(a32*a37);
  a37=(-a37);
  if (res[0]!=0) res[0][18]=a37;
  a61=(a32*a61);
  a27=(a27*a68);
  a30=(a30*a34);
  a27=(a27-a30);
  a61=(a61+a27);
  if (res[0]!=0) res[0][19]=a61;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a16;
  if (res[0]!=0) res[0][22]=a27;
  a41=(a41*a17);
  a41=(a18+a41);
  a18=(a18/a8);
  a43=(a18*a43);
  a43=(a41-a43);
  a47=(a9*a47);
  a43=(a43+a47);
  a50=(a15*a50);
  a43=(a43+a50);
  if (res[0]!=0) res[0][23]=a43;
  if (res[0]!=0) res[0][24]=a15;
  a14=(a9*a14);
  if (res[0]!=0) res[0][25]=a14;
  a23=(a9*a23);
  a56=(a15*a56);
  a23=(a23+a56);
  if (res[0]!=0) res[0][26]=a23;
  a18=(a18*a60);
  a41=(a41-a18);
  a9=(a9*a38);
  a41=(a41+a9);
  a15=(a15*a62);
  a41=(a41+a15);
  if (res[0]!=0) res[0][27]=a41;
  a48=(a13*a48);
  a49=(a2*a49);
  a48=(a48-a49);
  if (res[0]!=0) res[0][28]=a48;
  a53=(a13*a53);
  a52=(a2*a52);
  a53=(a53-a52);
  if (res[0]!=0) res[0][29]=a53;
  a55=(a13*a55);
  a51=(a2*a51);
  a55=(a55-a51);
  if (res[0]!=0) res[0][30]=a55;
  a57=(a13*a57);
  a58=(a2*a58);
  a57=(a57-a58);
  if (res[0]!=0) res[0][31]=a57;
  a13=(a13*a19);
  a2=(a2*a7);
  a13=(a13-a2);
  if (res[0]!=0) res[0][32]=a13;
  a12=(a22*a12);
  if (res[0]!=0) res[0][33]=a12;
  a66=(a22*a66);
  if (res[0]!=0) res[0][34]=a66;
  a22=(a22*a25);
  if (res[0]!=0) res[0][35]=a22;
  a5=(a24*a5);
  if (res[0]!=0) res[0][36]=a5;
  a65=(a24*a65);
  if (res[0]!=0) res[0][37]=a65;
  a24=(a24*a21);
  if (res[0]!=0) res[0][38]=a24;
  a24=1.2000000000000000e+000;
  if (res[0]!=0) res[0][39]=a24;
  a42=(a35*a42);
  a45=(a20*a45);
  a42=(a42+a45);
  a46=(a32*a46);
  a42=(a42-a46);
  if (res[0]!=0) res[0][40]=a42;
  a54=(a20*a54);
  a3=(a32*a3);
  a54=(a54+a3);
  if (res[0]!=0) res[0][41]=a54;
  a10=(a32*a10);
  if (res[0]!=0) res[0][42]=a10;
  a35=(a35*a40);
  a20=(a20*a39);
  a35=(a35+a20);
  a32=(a32*a4);
  a35=(a35-a32);
  if (res[0]!=0) res[0][43]=a35;
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_f_getMetabolicEnergySmooth2004all(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jac_f_getMetabolicEnergySmooth2004all_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_f_getMetabolicEnergySmooth2004all_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_f_getMetabolicEnergySmooth2004all_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jac_f_getMetabolicEnergySmooth2004all_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_f_getMetabolicEnergySmooth2004all_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jac_f_getMetabolicEnergySmooth2004all_incref(void) {
}

CASADI_SYMBOL_EXPORT void jac_f_getMetabolicEnergySmooth2004all_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jac_f_getMetabolicEnergySmooth2004all_n_in(void) { return 18;}

CASADI_SYMBOL_EXPORT casadi_int jac_f_getMetabolicEnergySmooth2004all_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real jac_f_getMetabolicEnergySmooth2004all_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_f_getMetabolicEnergySmooth2004all_name_in(casadi_int i){
  switch (i) {
    case 0: return "exc_SX";
    case 1: return "act_SX";
    case 2: return "lMtilde_SX";
    case 3: return "vM_SX";
    case 4: return "FT_SX";
    case 5: return "FT_SX";
    case 6: return "musclemass_SX";
    case 7: return "pctst_SX";
    case 8: return "Fiso_SX";
    case 9: return "FMo_SX";
    case 10: return "modelmass_SX";
    case 11: return "b_SX";
    case 12: return "out_Edot";
    case 13: return "out_Adot";
    case 14: return "out_Mdot";
    case 15: return "out_Sdot";
    case 16: return "out_Wdot";
    case 17: return "out_Edot+basal";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_f_getMetabolicEnergySmooth2004all_name_out(casadi_int i){
  switch (i) {
    case 0: return "jac";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_f_getMetabolicEnergySmooth2004all_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s1;
    case 13: return casadi_s1;
    case 14: return casadi_s1;
    case 15: return casadi_s1;
    case 16: return casadi_s1;
    case 17: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_f_getMetabolicEnergySmooth2004all_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jac_f_getMetabolicEnergySmooth2004all_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
