/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) muscle_contraction_dynamics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[4] = {1, 1, 0, 0};
static const casadi_int casadi_s2[72] = {7, 17, 0, 2, 7, 9, 13, 15, 19, 24, 28, 32, 35, 36, 40, 44, 46, 48, 50, 52, 0, 2, 0, 1, 2, 3, 4, 0, 2, 0, 2, 3, 4, 0, 2, 1, 2, 3, 6, 0, 2, 3, 4, 6, 0, 2, 3, 4, 0, 2, 3, 4, 0, 2, 5, 6, 0, 2, 3, 4, 0, 2, 3, 4, 0, 2, 0, 3, 0, 3, 0, 2};
static const casadi_int casadi_s3[24] = {2, 7, 0, 2, 4, 6, 8, 10, 12, 14, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s4[32] = {2, 10, 0, 2, 4, 6, 8, 10, 11, 13, 15, 17, 19, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s5[22] = {2, 10, 0, 2, 3, 3, 5, 5, 5, 5, 5, 7, 9, 0, 1, 1, 0, 1, 0, 1, 0, 1};

/* f_ForceEquilibrium_FtildeState_all_tendon:(a,FTtilde,dFTtilde,lMT,vMT,FMo,lMo,lTs,alphao,vMmax,tension,tendon_stiff,tendon_stiff_shift,d,shift,scale,shift)->(Hilldiff,FT,Fce,Fpass,Fiso,vMmax,massM) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[16]? arg[16][0] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a0=(a0*a1);
  a1=8.1448347834300838e-001;
  a2=-5.0000000000000000e-001;
  a3=arg[6]? arg[6][0] : 0;
  a4=arg[8]? arg[8][0] : 0;
  a4=sin(a4);
  a4=(a3*a4);
  a4=casadi_sq(a4);
  a5=arg[3]? arg[3][0] : 0;
  a6=arg[7]? arg[7][0] : 0;
  a7=5.;
  a8=arg[1]? arg[1][0] : 0;
  a9=2.5000000000000000e-001;
  a9=(a8+a9);
  a10=arg[12]? arg[12][0] : 0;
  a9=(a9-a10);
  a7=(a7*a9);
  a7=log(a7);
  a9=arg[11]? arg[11][0] : 0;
  a10=(a7/a9);
  a11=9.9500000000000000e-001;
  a10=(a10+a11);
  a11=(a6*a10);
  a11=(a5-a11);
  a11=casadi_sq(a11);
  a4=(a4+a11);
  a4=sqrt(a4);
  a11=(a4/a3);
  a12=1.0550334289705745e+000;
  a12=(a11-a12);
  a12=casadi_sq(a12);
  a12=(a2*a12);
  a13=1.6238457359957373e-001;
  a14=6.3303448465464637e-002;
  a14=(a14*a11);
  a13=(a13+a14);
  a13=casadi_sq(a13);
  a12=(a12/a13);
  a12=exp(a12);
  a1=(a1*a12);
  a12=4.3300498439264734e-001;
  a13=7.1677541339776030e-001;
  a13=(a11-a13);
  a13=casadi_sq(a13);
  a13=(a2*a13);
  a14=-2.9947116970695593e-002;
  a15=2.0035684729618783e-001;
  a15=(a15*a11);
  a14=(a14+a15);
  a14=casadi_sq(a14);
  a13=(a13/a14);
  a13=exp(a13);
  a12=(a12*a13);
  a1=(a1+a12);
  a12=1.0000000000000001e-001;
  a13=1.;
  a14=(a11-a13);
  a14=casadi_sq(a14);
  a2=(a2*a14);
  a14=1.2500000000000003e-001;
  a2=(a2/a14);
  a2=exp(a2);
  a12=(a12*a2);
  a1=(a1+a12);
  a0=(a0*a1);
  a12=-3.1832343689912745e-001;
  a2=-8.1491560434752497e+000;
  a14=arg[4]? arg[4][0] : 0;
  a15=arg[2]? arg[2][0] : 0;
  a15=(a6*a15);
  a16=2.0000000000000001e-001;
  a16=(a16*a9);
  a7=exp(a7);
  a16=(a16*a7);
  a15=(a15/a16);
  a14=(a14-a15);
  a6=(a6*a10);
  a5=(a5-a6);
  a5=(a5/a4);
  a14=(a14*a5);
  a4=arg[9]? arg[9][0] : 0;
  a14=(a14/a4);
  a6=(a2*a14);
  a10=-3.7412150864786309e-001;
  a6=(a6+a10);
  a2=(a2*a14);
  a2=(a2+a10);
  a2=casadi_sq(a2);
  a2=(a2+a13);
  a2=sqrt(a2);
  a6=(a6+a2);
  a6=log(a6);
  a12=(a12*a6);
  a6=8.8564405991500383e-001;
  a12=(a12+a6);
  a0=(a0*a12);
  a12=arg[13]? arg[13][0] : 0;
  a12=(a12*a14);
  a0=(a0+a12);
  a12=4.;
  a14=arg[14]? arg[14][0] : 0;
  a11=(a11-a14);
  a12=(a12*a11);
  a11=5.9999999999999998e-001;
  a14=arg[15]? arg[15][0] : 0;
  a11=(a11/a14);
  a12=(a12/a11);
  a12=exp(a12);
  a12=(a12-a13);
  a13=-9.9517205000616860e-001;
  a12=(a12-a13);
  a13=5.3598150033144236e+001;
  a12=(a12/a13);
  a13=(a0+a12);
  a13=(a13*a5);
  a13=(a13-a8);
  if (res[0]!=0) res[0][0]=a13;
  a13=arg[5]? arg[5][0] : 0;
  a8=(a8*a13);
  if (res[1]!=0) res[1][0]=a8;
  a0=(a13*a0);
  if (res[2]!=0) res[2][0]=a0;
  a12=(a13*a12);
  if (res[3]!=0) res[3][0]=a12;
  if (res[4]!=0) res[4][0]=a1;
  if (res[5]!=0) res[5][0]=a4;
  a4=1.0597000000000000e+003;
  a13=(a13*a3);
  a4=(a4*a13);
  a13=1000000.;
  a3=arg[10]? arg[10][0] : 0;
  a13=(a13*a3);
  a4=(a4/a13);
  if (res[6]!=0) res[6][0]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_ForceEquilibrium_FtildeState_all_tendon(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_ForceEquilibrium_FtildeState_all_tendon_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_ForceEquilibrium_FtildeState_all_tendon_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_ForceEquilibrium_FtildeState_all_tendon_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_ForceEquilibrium_FtildeState_all_tendon_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_ForceEquilibrium_FtildeState_all_tendon_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_ForceEquilibrium_FtildeState_all_tendon_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_ForceEquilibrium_FtildeState_all_tendon_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_ForceEquilibrium_FtildeState_all_tendon_n_in(void) { return 17;}

CASADI_SYMBOL_EXPORT casadi_int f_ForceEquilibrium_FtildeState_all_tendon_n_out(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_real f_ForceEquilibrium_FtildeState_all_tendon_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_ForceEquilibrium_FtildeState_all_tendon_name_in(casadi_int i){
  switch (i) {
    case 0: return "a";
    case 1: return "FTtilde";
    case 2: return "dFTtilde";
    case 3: return "lMT";
    case 4: return "vMT";
    case 5: return "FMo";
    case 6: return "lMo";
    case 7: return "lTs";
    case 8: return "alphao";
    case 9: return "vMmax";
    case 10: return "tension";
    case 11: return "tendon_stiff";
    case 12: return "tendon_stiff_shift";
    case 13: return "d";
    case 14: return "shift";
    case 15: return "scale";
    case 16: return "shift";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_ForceEquilibrium_FtildeState_all_tendon_name_out(casadi_int i){
  switch (i) {
    case 0: return "Hilldiff";
    case 1: return "FT";
    case 2: return "Fce";
    case 3: return "Fpass";
    case 4: return "Fiso";
    case 5: return "vMmax";
    case 6: return "massM";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_ForceEquilibrium_FtildeState_all_tendon_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    case 14: return casadi_s0;
    case 15: return casadi_s0;
    case 16: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_ForceEquilibrium_FtildeState_all_tendon_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_ForceEquilibrium_FtildeState_all_tendon_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* f_FiberLength_TendonForce_tendon:(FTtilde,lMo,lTs,alphao,lMT,tendon_stiff,tendon_stiff_shift)->(lM,lMtilde) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a1=sin(a1);
  a1=(a0*a1);
  a1=casadi_sq(a1);
  a2=arg[4]? arg[4][0] : 0;
  a3=arg[2]? arg[2][0] : 0;
  a4=5.;
  a5=arg[0]? arg[0][0] : 0;
  a6=2.5000000000000000e-001;
  a5=(a5+a6);
  a6=arg[6]? arg[6][0] : 0;
  a5=(a5-a6);
  a4=(a4*a5);
  a4=log(a4);
  a5=arg[5]? arg[5][0] : 0;
  a4=(a4/a5);
  a5=9.9500000000000000e-001;
  a4=(a4+a5);
  a3=(a3*a4);
  a2=(a2-a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a1=sqrt(a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=(a1/a0);
  if (res[1]!=0) res[1][0]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_FiberLength_TendonForce_tendon(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_FiberLength_TendonForce_tendon_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_FiberLength_TendonForce_tendon_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_FiberLength_TendonForce_tendon_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_FiberLength_TendonForce_tendon_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_FiberLength_TendonForce_tendon_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_FiberLength_TendonForce_tendon_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_FiberLength_TendonForce_tendon_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_FiberLength_TendonForce_tendon_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int f_FiberLength_TendonForce_tendon_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real f_FiberLength_TendonForce_tendon_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_FiberLength_TendonForce_tendon_name_in(casadi_int i){
  switch (i) {
    case 0: return "FTtilde";
    case 1: return "lMo";
    case 2: return "lTs";
    case 3: return "alphao";
    case 4: return "lMT";
    case 5: return "tendon_stiff";
    case 6: return "tendon_stiff_shift";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_FiberLength_TendonForce_tendon_name_out(casadi_int i){
  switch (i) {
    case 0: return "lM";
    case 1: return "lMtilde";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_FiberLength_TendonForce_tendon_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_FiberLength_TendonForce_tendon_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_FiberLength_TendonForce_tendon_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* f_FiberVelocity_TendonForce_tendon:(FTtilde,dFTtilde,lMo,lTs,alphao,vMmax,lMT,vMT,tendon_stiff,tendon_stiff_shift)->(vM,vMtilde) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=arg[7]? arg[7][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a2=(a1*a2);
  a3=2.0000000000000001e-001;
  a4=arg[8]? arg[8][0] : 0;
  a3=(a3*a4);
  a5=5.;
  a6=arg[0]? arg[0][0] : 0;
  a7=2.5000000000000000e-001;
  a6=(a6+a7);
  a7=arg[9]? arg[9][0] : 0;
  a6=(a6-a7);
  a5=(a5*a6);
  a5=log(a5);
  a6=exp(a5);
  a3=(a3*a6);
  a2=(a2/a3);
  a0=(a0-a2);
  a2=arg[6]? arg[6][0] : 0;
  a5=(a5/a4);
  a4=9.9500000000000000e-001;
  a5=(a5+a4);
  a4=(a1*a5);
  a4=(a2-a4);
  a3=arg[2]? arg[2][0] : 0;
  a6=arg[4]? arg[4][0] : 0;
  a6=sin(a6);
  a3=(a3*a6);
  a3=casadi_sq(a3);
  a1=(a1*a5);
  a2=(a2-a1);
  a2=casadi_sq(a2);
  a3=(a3+a2);
  a3=sqrt(a3);
  a4=(a4/a3);
  a0=(a0*a4);
  if (res[0]!=0) res[0][0]=a0;
  a4=arg[5]? arg[5][0] : 0;
  a0=(a0/a4);
  if (res[1]!=0) res[1][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_FiberVelocity_TendonForce_tendon(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_FiberVelocity_TendonForce_tendon_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_FiberVelocity_TendonForce_tendon_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_FiberVelocity_TendonForce_tendon_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_FiberVelocity_TendonForce_tendon_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_FiberVelocity_TendonForce_tendon_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_FiberVelocity_TendonForce_tendon_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_FiberVelocity_TendonForce_tendon_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_FiberVelocity_TendonForce_tendon_n_in(void) { return 10;}

CASADI_SYMBOL_EXPORT casadi_int f_FiberVelocity_TendonForce_tendon_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real f_FiberVelocity_TendonForce_tendon_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_FiberVelocity_TendonForce_tendon_name_in(casadi_int i){
  switch (i) {
    case 0: return "FTtilde";
    case 1: return "dFTtilde";
    case 2: return "lMo";
    case 3: return "lTs";
    case 4: return "alphao";
    case 5: return "vMmax";
    case 6: return "lMT";
    case 7: return "vMT";
    case 8: return "tendon_stiff";
    case 9: return "tendon_stiff_shift";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_FiberVelocity_TendonForce_tendon_name_out(casadi_int i){
  switch (i) {
    case 0: return "vM";
    case 1: return "vMtilde";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_FiberVelocity_TendonForce_tendon_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_FiberVelocity_TendonForce_tendon_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_FiberVelocity_TendonForce_tendon_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* f_lT_vT:(FTtilde,dFTtilde,lMo,lTs,alphao,vMmax,lMT,vMT,tendon_stiff,tendon_stiff_shift)->(lT,vT) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=arg[3]? arg[3][0] : 0;
  a1=5.;
  a2=arg[0]? arg[0][0] : 0;
  a3=2.5000000000000000e-001;
  a4=(a2+a3);
  a5=arg[9]? arg[9][0] : 0;
  a4=(a4-a5);
  a4=(a1*a4);
  a4=log(a4);
  a6=arg[8]? arg[8][0] : 0;
  a4=(a4/a6);
  a7=9.9500000000000000e-001;
  a4=(a4+a7);
  a4=(a0*a4);
  if (res[0]!=0) res[0][0]=a4;
  a4=arg[1]? arg[1][0] : 0;
  a0=(a0*a4);
  a4=2.0000000000000001e-001;
  a4=(a4*a6);
  a2=(a2+a3);
  a2=(a2-a5);
  a1=(a1*a2);
  a1=log(a1);
  a1=exp(a1);
  a4=(a4*a1);
  a0=(a0/a4);
  if (res[1]!=0) res[1][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_lT_vT(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_lT_vT_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_lT_vT_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_lT_vT_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_lT_vT_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_lT_vT_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_lT_vT_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_lT_vT_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_lT_vT_n_in(void) { return 10;}

CASADI_SYMBOL_EXPORT casadi_int f_lT_vT_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real f_lT_vT_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_lT_vT_name_in(casadi_int i){
  switch (i) {
    case 0: return "FTtilde";
    case 1: return "dFTtilde";
    case 2: return "lMo";
    case 3: return "lTs";
    case 4: return "alphao";
    case 5: return "vMmax";
    case 6: return "lMT";
    case 7: return "vMT";
    case 8: return "tendon_stiff";
    case 9: return "tendon_stiff_shift";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_lT_vT_name_out(casadi_int i){
  switch (i) {
    case 0: return "lT";
    case 1: return "vT";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_lT_vT_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_lT_vT_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_lT_vT_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jac_f_ForceEquilibrium_FtildeState_all_tendon:(a,FTtilde,dFTtilde,lMT,vMT,FMo,lMo,lTs,alphao,vMmax,tension,tendon_stiff,tendon_stiff_shift,d,shift,scale,shift,out_Hilldiff[1x1,0nz],out_FT[1x1,0nz],out_Fce[1x1,0nz],out_Fpass[1x1,0nz],out_Fiso[1x1,0nz],out_vMmax[1x1,0nz],out_massM[1x1,0nz])->(jac[7x17,52nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a9;
  a0=arg[16]? arg[16][0] : 0;
  a1=8.1448347834300838e-001;
  a2=-5.0000000000000000e-001;
  a3=arg[6]? arg[6][0] : 0;
  a4=arg[8]? arg[8][0] : 0;
  a5=sin(a4);
  a6=(a3*a5);
  a7=casadi_sq(a6);
  a8=arg[3]? arg[3][0] : 0;
  a9=arg[7]? arg[7][0] : 0;
  a10=5.;
  a11=arg[1]? arg[1][0] : 0;
  a12=2.5000000000000000e-001;
  a12=(a11+a12);
  a13=arg[12]? arg[12][0] : 0;
  a12=(a12-a13);
  a12=(a10*a12);
  a13=log(a12);
  a14=arg[11]? arg[11][0] : 0;
  a15=(a13/a14);
  a16=9.9500000000000000e-001;
  a16=(a15+a16);
  a17=(a9*a16);
  a17=(a8-a17);
  a18=casadi_sq(a17);
  a7=(a7+a18);
  a7=sqrt(a7);
  a18=(a7/a3);
  a19=1.0550334289705745e+000;
  a19=(a18-a19);
  a20=casadi_sq(a19);
  a20=(a2*a20);
  a21=1.6238457359957373e-001;
  a22=6.3303448465464637e-002;
  a23=(a22*a18);
  a21=(a21+a23);
  a23=casadi_sq(a21);
  a20=(a20/a23);
  a24=exp(a20);
  a25=(a1*a24);
  a26=4.3300498439264734e-001;
  a27=7.1677541339776030e-001;
  a27=(a18-a27);
  a28=casadi_sq(a27);
  a28=(a2*a28);
  a29=-2.9947116970695593e-002;
  a30=2.0035684729618783e-001;
  a31=(a30*a18);
  a29=(a29+a31);
  a31=casadi_sq(a29);
  a28=(a28/a31);
  a32=exp(a28);
  a33=(a26*a32);
  a25=(a25+a33);
  a33=1.0000000000000001e-001;
  a34=1.;
  a35=(a18-a34);
  a36=casadi_sq(a35);
  a36=(a2*a36);
  a37=1.2500000000000003e-001;
  a36=(a36/a37);
  a36=exp(a36);
  a37=(a33*a36);
  a25=(a25+a37);
  a37=-3.1832343689912745e-001;
  a38=-8.1491560434752497e+000;
  a39=arg[4]? arg[4][0] : 0;
  a40=arg[2]? arg[2][0] : 0;
  a41=(a9*a40);
  a42=2.0000000000000001e-001;
  a43=(a42*a14);
  a13=exp(a13);
  a44=(a43*a13);
  a41=(a41/a44);
  a39=(a39-a41);
  a45=(a9*a16);
  a8=(a8-a45);
  a8=(a8/a7);
  a45=(a39*a8);
  a46=arg[9]? arg[9][0] : 0;
  a45=(a45/a46);
  a47=(a38*a45);
  a48=-3.7412150864786309e-001;
  a47=(a47+a48);
  a49=(a38*a45);
  a49=(a49+a48);
  a48=casadi_sq(a49);
  a48=(a48+a34);
  a48=sqrt(a48);
  a47=(a47+a48);
  a50=log(a47);
  a50=(a37*a50);
  a51=8.8564405991500383e-001;
  a50=(a50+a51);
  a51=(a50*a8);
  a52=(a25*a51);
  a53=(a0*a52);
  if (res[0]!=0) res[0][0]=a53;
  a53=arg[5]? arg[5][0] : 0;
  a54=(a50*a53);
  a55=(a25*a54);
  a56=(a0*a55);
  if (res[0]!=0) res[0][1]=a56;
  a56=-1.;
  a41=(a41/a44);
  a57=arg[13]? arg[13][0] : 0;
  a58=(a57*a8);
  a49=(a49+a49);
  a59=arg[0]? arg[0][0] : 0;
  a0=(a0*a59);
  a25=(a0*a25);
  a60=(a25*a8);
  a60=(a37*a60);
  a60=(a60/a47);
  a48=(a48+a48);
  a61=(a60/a48);
  a61=(a49*a61);
  a61=(a38*a61);
  a58=(a58+a61);
  a60=(a38*a60);
  a58=(a58+a60);
  a60=(a58/a46);
  a61=(a8*a60);
  a62=(a41*a61);
  a63=(a43*a62);
  a63=(a13*a63);
  a50=(a25*a50);
  a64=(a57*a45);
  a50=(a50+a64);
  a64=4.;
  a65=arg[14]? arg[14][0] : 0;
  a65=(a18-a65);
  a65=(a64*a65);
  a66=5.9999999999999998e-001;
  a67=arg[15]? arg[15][0] : 0;
  a66=(a66/a67);
  a65=(a65/a66);
  a68=exp(a65);
  a69=(a68-a34);
  a70=-9.9517205000616860e-001;
  a69=(a69-a70);
  a70=5.3598150033144236e+001;
  a69=(a69/a70);
  a70=(a50+a69);
  a60=(a39*a60);
  a70=(a70+a60);
  a60=(a70/a7);
  a71=(a9*a60);
  a17=(a17+a17);
  a72=1.8657360363774050e-002;
  a73=(a72*a8);
  a73=(a68*a73);
  a74=(a73/a66);
  a74=(a64*a74);
  a35=(a35+a35);
  a75=7.9999999999999982e+000;
  a51=(a0*a51);
  a76=(a33*a51);
  a76=(a36*a76);
  a76=(a75*a76);
  a76=(a2*a76);
  a76=(a35*a76);
  a76=(a74+a76);
  a29=(a29+a29);
  a28=(a28/a31);
  a77=(a26*a51);
  a77=(a32*a77);
  a78=(a28*a77);
  a78=(a29*a78);
  a78=(a30*a78);
  a76=(a76-a78);
  a27=(a27+a27);
  a77=(a77/a31);
  a77=(a2*a77);
  a77=(a27*a77);
  a76=(a76+a77);
  a21=(a21+a21);
  a20=(a20/a23);
  a51=(a1*a51);
  a51=(a24*a51);
  a77=(a20*a51);
  a77=(a21*a77);
  a77=(a22*a77);
  a76=(a76-a77);
  a19=(a19+a19);
  a51=(a51/a23);
  a51=(a2*a51);
  a51=(a19*a51);
  a76=(a76+a51);
  a51=(a76/a3);
  a77=(a8/a7);
  a70=(a77*a70);
  a51=(a51-a70);
  a70=(a7+a7);
  a51=(a51/a70);
  a78=(a17*a51);
  a79=(a9*a78);
  a71=(a71+a79);
  a79=(a71/a14);
  a63=(a63-a79);
  a63=(a63/a12);
  a63=(a10*a63);
  a56=(a56+a63);
  if (res[0]!=0) res[0][2]=a56;
  if (res[0]!=0) res[0][3]=a53;
  a57=(a57*a53);
  a25=(a25*a53);
  a37=(a37*a25);
  a37=(a37/a47);
  a48=(a37/a48);
  a49=(a49*a48);
  a49=(a38*a49);
  a57=(a57+a49);
  a38=(a38*a37);
  a57=(a57+a38);
  a38=(a57/a46);
  a37=(a8*a38);
  a41=(a41*a37);
  a43=(a43*a41);
  a43=(a13*a43);
  a39=(a39*a38);
  a7=(a39/a7);
  a38=(a9*a7);
  a0=(a0*a54);
  a54=(a33*a0);
  a54=(a36*a54);
  a54=(a75*a54);
  a54=(a2*a54);
  a54=(a35*a54);
  a49=(a26*a0);
  a49=(a32*a49);
  a48=(a28*a49);
  a48=(a29*a48);
  a48=(a30*a48);
  a54=(a54-a48);
  a49=(a49/a31);
  a49=(a2*a49);
  a49=(a27*a49);
  a54=(a54+a49);
  a0=(a1*a0);
  a0=(a24*a0);
  a49=(a20*a0);
  a49=(a21*a49);
  a49=(a22*a49);
  a54=(a54-a49);
  a0=(a0/a23);
  a0=(a2*a0);
  a0=(a19*a0);
  a54=(a54+a0);
  a0=(a54/a3);
  a77=(a77*a39);
  a0=(a0-a77);
  a0=(a0/a70);
  a77=(a17*a0);
  a39=(a9*a77);
  a38=(a38+a39);
  a39=(a38/a14);
  a43=(a43-a39);
  a43=(a43/a12);
  a43=(a10*a43);
  if (res[0]!=0) res[0][4]=a43;
  a72=(a72*a53);
  a68=(a68*a72);
  a72=(a68/a66);
  a64=(a64*a72);
  a72=(a64/a3);
  a72=(a72/a70);
  a39=(a17*a72);
  a49=(a9*a39);
  a48=(a49/a14);
  a48=(a48/a12);
  a48=(a10*a48);
  a47=(-a48);
  if (res[0]!=0) res[0][5]=a47;
  a33=(a33*a36);
  a75=(a75*a33);
  a75=(a2*a75);
  a35=(a35*a75);
  a26=(a26*a32);
  a28=(a28*a26);
  a29=(a29*a28);
  a30=(a30*a29);
  a35=(a35-a30);
  a26=(a26/a31);
  a26=(a2*a26);
  a27=(a27*a26);
  a35=(a35+a27);
  a1=(a1*a24);
  a20=(a20*a1);
  a21=(a21*a20);
  a22=(a22*a21);
  a35=(a35-a22);
  a1=(a1/a23);
  a2=(a2*a1);
  a19=(a19*a2);
  a35=(a35+a19);
  a19=(a35/a3);
  a19=(a19/a70);
  a17=(a17*a19);
  a70=(a9*a17);
  a2=(a70/a14);
  a2=(a2/a12);
  a10=(a10*a2);
  a2=(-a10);
  if (res[0]!=0) res[0][6]=a2;
  a2=(a61/a44);
  a12=(a9*a2);
  a12=(-a12);
  if (res[0]!=0) res[0][7]=a12;
  a44=(a37/a44);
  a9=(a9*a44);
  a9=(-a9);
  if (res[0]!=0) res[0][8]=a9;
  a9=(a60+a78);
  if (res[0]!=0) res[0][9]=a9;
  a9=(a7+a77);
  if (res[0]!=0) res[0][10]=a9;
  if (res[0]!=0) res[0][11]=a39;
  if (res[0]!=0) res[0][12]=a17;
  if (res[0]!=0) res[0][13]=a61;
  if (res[0]!=0) res[0][14]=a37;
  if (res[0]!=0) res[0][15]=a11;
  if (res[0]!=0) res[0][16]=a50;
  if (res[0]!=0) res[0][17]=a69;
  a69=1.0597000000000000e+003;
  a50=1000000.;
  a11=arg[10]? arg[10][0] : 0;
  a11=(a50*a11);
  a37=(a69/a11);
  a61=(a3*a37);
  if (res[0]!=0) res[0][18]=a61;
  a6=(a6+a6);
  a51=(a6*a51);
  a61=(a5*a51);
  a18=(a18/a3);
  a76=(a18*a76);
  a61=(a61-a76);
  if (res[0]!=0) res[0][19]=a61;
  a0=(a6*a0);
  a61=(a5*a0);
  a54=(a18*a54);
  a61=(a61-a54);
  if (res[0]!=0) res[0][20]=a61;
  a72=(a6*a72);
  a61=(a5*a72);
  a54=(a18*a64);
  a61=(a61-a54);
  if (res[0]!=0) res[0][21]=a61;
  a6=(a6*a19);
  a5=(a5*a6);
  a18=(a18*a35);
  a5=(a5-a18);
  if (res[0]!=0) res[0][22]=a5;
  a37=(a53*a37);
  if (res[0]!=0) res[0][23]=a37;
  a60=(a16*a60);
  a2=(a40*a2);
  a60=(a60+a2);
  a78=(a16*a78);
  a60=(a60+a78);
  a60=(-a60);
  if (res[0]!=0) res[0][24]=a60;
  a7=(a16*a7);
  a40=(a40*a44);
  a7=(a7+a40);
  a77=(a16*a77);
  a7=(a7+a77);
  a7=(-a7);
  if (res[0]!=0) res[0][25]=a7;
  a39=(a16*a39);
  a39=(-a39);
  if (res[0]!=0) res[0][26]=a39;
  a16=(a16*a17);
  a16=(-a16);
  if (res[0]!=0) res[0][27]=a16;
  a4=cos(a4);
  a51=(a3*a51);
  a51=(a4*a51);
  if (res[0]!=0) res[0][28]=a51;
  a0=(a3*a0);
  a0=(a4*a0);
  if (res[0]!=0) res[0][29]=a0;
  a72=(a3*a72);
  a72=(a4*a72);
  if (res[0]!=0) res[0][30]=a72;
  a6=(a3*a6);
  a4=(a4*a6);
  if (res[0]!=0) res[0][31]=a4;
  a46=(a45/a46);
  a58=(a46*a58);
  a58=(-a58);
  if (res[0]!=0) res[0][32]=a58;
  a46=(a46*a57);
  a46=(-a46);
  if (res[0]!=0) res[0][33]=a46;
  if (res[0]!=0) res[0][34]=a34;
  a3=(a53*a3);
  a69=(a69*a3);
  a69=(a69/a11);
  a69=(a69/a11);
  a50=(a50*a69);
  a50=(-a50);
  if (res[0]!=0) res[0][35]=a50;
  a62=(a13*a62);
  a62=(a42*a62);
  a15=(a15/a14);
  a71=(a15*a71);
  a62=(a62+a71);
  if (res[0]!=0) res[0][36]=a62;
  a13=(a13*a41);
  a42=(a42*a13);
  a38=(a15*a38);
  a42=(a42+a38);
  if (res[0]!=0) res[0][37]=a42;
  a49=(a15*a49);
  if (res[0]!=0) res[0][38]=a49;
  a15=(a15*a70);
  if (res[0]!=0) res[0][39]=a15;
  a63=(-a63);
  if (res[0]!=0) res[0][40]=a63;
  a43=(-a43);
  if (res[0]!=0) res[0][41]=a43;
  if (res[0]!=0) res[0][42]=a48;
  if (res[0]!=0) res[0][43]=a10;
  a8=(a45*a8);
  if (res[0]!=0) res[0][44]=a8;
  a45=(a45*a53);
  if (res[0]!=0) res[0][45]=a45;
  a74=(-a74);
  if (res[0]!=0) res[0][46]=a74;
  a64=(-a64);
  if (res[0]!=0) res[0][47]=a64;
  a67=(a66/a67);
  a65=(a65/a66);
  a73=(a65*a73);
  a73=(a67*a73);
  if (res[0]!=0) res[0][48]=a73;
  a65=(a65*a68);
  a67=(a67*a65);
  if (res[0]!=0) res[0][49]=a67;
  a52=(a59*a52);
  if (res[0]!=0) res[0][50]=a52;
  a59=(a59*a55);
  if (res[0]!=0) res[0][51]=a59;
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_f_ForceEquilibrium_FtildeState_all_tendon(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jac_f_ForceEquilibrium_FtildeState_all_tendon_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_f_ForceEquilibrium_FtildeState_all_tendon_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_f_ForceEquilibrium_FtildeState_all_tendon_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jac_f_ForceEquilibrium_FtildeState_all_tendon_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_f_ForceEquilibrium_FtildeState_all_tendon_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jac_f_ForceEquilibrium_FtildeState_all_tendon_incref(void) {
}

CASADI_SYMBOL_EXPORT void jac_f_ForceEquilibrium_FtildeState_all_tendon_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jac_f_ForceEquilibrium_FtildeState_all_tendon_n_in(void) { return 24;}

CASADI_SYMBOL_EXPORT casadi_int jac_f_ForceEquilibrium_FtildeState_all_tendon_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real jac_f_ForceEquilibrium_FtildeState_all_tendon_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_f_ForceEquilibrium_FtildeState_all_tendon_name_in(casadi_int i){
  switch (i) {
    case 0: return "a";
    case 1: return "FTtilde";
    case 2: return "dFTtilde";
    case 3: return "lMT";
    case 4: return "vMT";
    case 5: return "FMo";
    case 6: return "lMo";
    case 7: return "lTs";
    case 8: return "alphao";
    case 9: return "vMmax";
    case 10: return "tension";
    case 11: return "tendon_stiff";
    case 12: return "tendon_stiff_shift";
    case 13: return "d";
    case 14: return "shift";
    case 15: return "scale";
    case 16: return "shift";
    case 17: return "out_Hilldiff";
    case 18: return "out_FT";
    case 19: return "out_Fce";
    case 20: return "out_Fpass";
    case 21: return "out_Fiso";
    case 22: return "out_vMmax";
    case 23: return "out_massM";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_f_ForceEquilibrium_FtildeState_all_tendon_name_out(casadi_int i){
  switch (i) {
    case 0: return "jac";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_f_ForceEquilibrium_FtildeState_all_tendon_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    case 14: return casadi_s0;
    case 15: return casadi_s0;
    case 16: return casadi_s0;
    case 17: return casadi_s1;
    case 18: return casadi_s1;
    case 19: return casadi_s1;
    case 20: return casadi_s1;
    case 21: return casadi_s1;
    case 22: return casadi_s1;
    case 23: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_f_ForceEquilibrium_FtildeState_all_tendon_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jac_f_ForceEquilibrium_FtildeState_all_tendon_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 24;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jac_f_FiberLength_TendonForce_tendon:(FTtilde,lMo,lTs,alphao,lMT,tendon_stiff,tendon_stiff_shift,out_lM[1x1,0nz],out_lMtilde[1x1,0nz])->(jac[2x7]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=5.;
  a1=arg[2]? arg[2][0] : 0;
  a2=arg[4]? arg[4][0] : 0;
  a3=arg[0]? arg[0][0] : 0;
  a4=2.5000000000000000e-001;
  a3=(a3+a4);
  a4=arg[6]? arg[6][0] : 0;
  a3=(a3-a4);
  a3=(a0*a3);
  a4=log(a3);
  a5=arg[5]? arg[5][0] : 0;
  a4=(a4/a5);
  a6=9.9500000000000000e-001;
  a6=(a4+a6);
  a7=(a1*a6);
  a2=(a2-a7);
  a7=arg[1]? arg[1][0] : 0;
  a8=arg[3]? arg[3][0] : 0;
  a9=sin(a8);
  a10=(a7*a9);
  a11=casadi_sq(a10);
  a12=casadi_sq(a2);
  a11=(a11+a12);
  a11=sqrt(a11);
  a12=(a2/a11);
  a13=(a1*a12);
  a14=(a13/a5);
  a14=(a14/a3);
  a14=(a0*a14);
  a15=(-a14);
  if (res[0]!=0) res[0][0]=a15;
  a2=(a2+a2);
  a15=(a11+a11);
  a15=(1./a15);
  a15=(a15/a7);
  a2=(a2*a15);
  a1=(a1*a2);
  a16=(a1/a5);
  a16=(a16/a3);
  a0=(a0*a16);
  a16=(-a0);
  if (res[0]!=0) res[0][1]=a16;
  a16=(a10/a11);
  a3=(a9*a16);
  if (res[0]!=0) res[0][2]=a3;
  a10=(a10+a10);
  a10=(a10*a15);
  a9=(a9*a10);
  a11=(a11/a7);
  a11=(a11/a7);
  a9=(a9-a11);
  if (res[0]!=0) res[0][3]=a9;
  a9=(a6*a12);
  a9=(-a9);
  if (res[0]!=0) res[0][4]=a9;
  a6=(a6*a2);
  a6=(-a6);
  if (res[0]!=0) res[0][5]=a6;
  a8=cos(a8);
  a16=(a7*a16);
  a16=(a8*a16);
  if (res[0]!=0) res[0][6]=a16;
  a7=(a7*a10);
  a8=(a8*a7);
  if (res[0]!=0) res[0][7]=a8;
  if (res[0]!=0) res[0][8]=a12;
  if (res[0]!=0) res[0][9]=a2;
  a4=(a4/a5);
  a13=(a4*a13);
  if (res[0]!=0) res[0][10]=a13;
  a4=(a4*a1);
  if (res[0]!=0) res[0][11]=a4;
  if (res[0]!=0) res[0][12]=a14;
  if (res[0]!=0) res[0][13]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_f_FiberLength_TendonForce_tendon(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jac_f_FiberLength_TendonForce_tendon_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_f_FiberLength_TendonForce_tendon_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_f_FiberLength_TendonForce_tendon_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jac_f_FiberLength_TendonForce_tendon_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_f_FiberLength_TendonForce_tendon_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jac_f_FiberLength_TendonForce_tendon_incref(void) {
}

CASADI_SYMBOL_EXPORT void jac_f_FiberLength_TendonForce_tendon_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jac_f_FiberLength_TendonForce_tendon_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int jac_f_FiberLength_TendonForce_tendon_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real jac_f_FiberLength_TendonForce_tendon_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_f_FiberLength_TendonForce_tendon_name_in(casadi_int i){
  switch (i) {
    case 0: return "FTtilde";
    case 1: return "lMo";
    case 2: return "lTs";
    case 3: return "alphao";
    case 4: return "lMT";
    case 5: return "tendon_stiff";
    case 6: return "tendon_stiff_shift";
    case 7: return "out_lM";
    case 8: return "out_lMtilde";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_f_FiberLength_TendonForce_tendon_name_out(casadi_int i){
  switch (i) {
    case 0: return "jac";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_f_FiberLength_TendonForce_tendon_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s1;
    case 8: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_f_FiberLength_TendonForce_tendon_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jac_f_FiberLength_TendonForce_tendon_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jac_f_FiberVelocity_TendonForce_tendon:(FTtilde,dFTtilde,lMo,lTs,alphao,vMmax,lMT,vMT,tendon_stiff,tendon_stiff_shift,out_vM[1x1,0nz],out_vMtilde[1x1,0nz])->(jac[2x10,19nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a4, a5, a6, a7, a8, a9;
  a0=5.;
  a1=arg[3]? arg[3][0] : 0;
  a2=arg[6]? arg[6][0] : 0;
  a3=arg[0]? arg[0][0] : 0;
  a4=2.5000000000000000e-001;
  a3=(a3+a4);
  a4=arg[9]? arg[9][0] : 0;
  a3=(a3-a4);
  a3=(a0*a3);
  a4=log(a3);
  a5=arg[8]? arg[8][0] : 0;
  a6=(a4/a5);
  a7=9.9500000000000000e-001;
  a7=(a6+a7);
  a8=(a1*a7);
  a8=(a2-a8);
  a9=(a8+a8);
  a10=(a1*a7);
  a2=(a2-a10);
  a10=arg[2]? arg[2][0] : 0;
  a11=arg[4]? arg[4][0] : 0;
  a12=sin(a11);
  a13=(a10*a12);
  a14=casadi_sq(a13);
  a8=casadi_sq(a8);
  a14=(a14+a8);
  a14=sqrt(a14);
  a2=(a2/a14);
  a8=(a2/a14);
  a15=arg[7]? arg[7][0] : 0;
  a16=arg[1]? arg[1][0] : 0;
  a17=(a1*a16);
  a18=2.0000000000000001e-001;
  a19=(a18*a5);
  a4=exp(a4);
  a20=(a19*a4);
  a17=(a17/a20);
  a15=(a15-a17);
  a21=(a8*a15);
  a22=(a14+a14);
  a21=(a21/a22);
  a23=(a9*a21);
  a24=(a1*a23);
  a25=(a15/a14);
  a26=(a1*a25);
  a24=(a24-a26);
  a26=(a24/a5);
  a17=(a17/a20);
  a27=(a17*a2);
  a28=(a19*a27);
  a28=(a4*a28);
  a26=(a26+a28);
  a26=(a26/a3);
  a26=(a0*a26);
  if (res[0]!=0) res[0][0]=a26;
  a28=arg[5]? arg[5][0] : 0;
  a29=(a15/a28);
  a8=(a8*a29);
  a8=(a8/a22);
  a9=(a9*a8);
  a22=(a1*a9);
  a29=(a29/a14);
  a14=(a1*a29);
  a22=(a22-a14);
  a14=(a22/a5);
  a30=(a2/a28);
  a17=(a17*a30);
  a19=(a19*a17);
  a19=(a4*a19);
  a14=(a14+a19);
  a14=(a14/a3);
  a0=(a0*a14);
  if (res[0]!=0) res[0][1]=a0;
  a14=(a2/a20);
  a3=(a1*a14);
  a3=(-a3);
  if (res[0]!=0) res[0][2]=a3;
  a20=(a30/a20);
  a1=(a1*a20);
  a1=(-a1);
  if (res[0]!=0) res[0][3]=a1;
  a13=(a13+a13);
  a21=(a13*a21);
  a1=(a12*a21);
  a1=(-a1);
  if (res[0]!=0) res[0][4]=a1;
  a13=(a13*a8);
  a12=(a12*a13);
  a12=(-a12);
  if (res[0]!=0) res[0][5]=a12;
  a12=(a7*a23);
  a8=(a7*a25);
  a12=(a12-a8);
  a14=(a16*a14);
  a12=(a12-a14);
  if (res[0]!=0) res[0][6]=a12;
  a12=(a7*a9);
  a7=(a7*a29);
  a12=(a12-a7);
  a16=(a16*a20);
  a12=(a12-a16);
  if (res[0]!=0) res[0][7]=a12;
  a11=cos(a11);
  a21=(a10*a21);
  a21=(a11*a21);
  a21=(-a21);
  if (res[0]!=0) res[0][8]=a21;
  a10=(a10*a13);
  a11=(a11*a10);
  a11=(-a11);
  if (res[0]!=0) res[0][9]=a11;
  a15=(a15*a2);
  a15=(a15/a28);
  a15=(a15/a28);
  a15=(-a15);
  if (res[0]!=0) res[0][10]=a15;
  a25=(a25-a23);
  if (res[0]!=0) res[0][11]=a25;
  a29=(a29-a9);
  if (res[0]!=0) res[0][12]=a29;
  if (res[0]!=0) res[0][13]=a2;
  if (res[0]!=0) res[0][14]=a30;
  a27=(a4*a27);
  a27=(a18*a27);
  a6=(a6/a5);
  a24=(a6*a24);
  a27=(a27-a24);
  if (res[0]!=0) res[0][15]=a27;
  a4=(a4*a17);
  a18=(a18*a4);
  a6=(a6*a22);
  a18=(a18-a6);
  if (res[0]!=0) res[0][16]=a18;
  a26=(-a26);
  if (res[0]!=0) res[0][17]=a26;
  a0=(-a0);
  if (res[0]!=0) res[0][18]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_f_FiberVelocity_TendonForce_tendon(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jac_f_FiberVelocity_TendonForce_tendon_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_f_FiberVelocity_TendonForce_tendon_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_f_FiberVelocity_TendonForce_tendon_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jac_f_FiberVelocity_TendonForce_tendon_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_f_FiberVelocity_TendonForce_tendon_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jac_f_FiberVelocity_TendonForce_tendon_incref(void) {
}

CASADI_SYMBOL_EXPORT void jac_f_FiberVelocity_TendonForce_tendon_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jac_f_FiberVelocity_TendonForce_tendon_n_in(void) { return 12;}

CASADI_SYMBOL_EXPORT casadi_int jac_f_FiberVelocity_TendonForce_tendon_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real jac_f_FiberVelocity_TendonForce_tendon_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_f_FiberVelocity_TendonForce_tendon_name_in(casadi_int i){
  switch (i) {
    case 0: return "FTtilde";
    case 1: return "dFTtilde";
    case 2: return "lMo";
    case 3: return "lTs";
    case 4: return "alphao";
    case 5: return "vMmax";
    case 6: return "lMT";
    case 7: return "vMT";
    case 8: return "tendon_stiff";
    case 9: return "tendon_stiff_shift";
    case 10: return "out_vM";
    case 11: return "out_vMtilde";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_f_FiberVelocity_TendonForce_tendon_name_out(casadi_int i){
  switch (i) {
    case 0: return "jac";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_f_FiberVelocity_TendonForce_tendon_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s1;
    case 11: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_f_FiberVelocity_TendonForce_tendon_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jac_f_FiberVelocity_TendonForce_tendon_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jac_f_lT_vT:(FTtilde,dFTtilde,lMo,lTs,alphao,vMmax,lMT,vMT,tendon_stiff,tendon_stiff_shift,out_lT[1x1,0nz],out_vT[1x1,0nz])->(jac[2x10,9nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=5.;
  a1=arg[3]? arg[3][0] : 0;
  a2=arg[8]? arg[8][0] : 0;
  a3=(a1/a2);
  a4=arg[0]? arg[0][0] : 0;
  a5=2.5000000000000000e-001;
  a6=(a4+a5);
  a7=arg[9]? arg[9][0] : 0;
  a6=(a6-a7);
  a6=(a0*a6);
  a3=(a3/a6);
  a3=(a0*a3);
  if (res[0]!=0) res[0][0]=a3;
  a4=(a4+a5);
  a4=(a4-a7);
  a4=(a0*a4);
  a7=log(a4);
  a7=exp(a7);
  a5=2.0000000000000001e-001;
  a8=(a5*a2);
  a9=arg[1]? arg[1][0] : 0;
  a10=(a1*a9);
  a11=(a8*a7);
  a10=(a10/a11);
  a10=(a10/a11);
  a8=(a8*a10);
  a8=(a7*a8);
  a8=(a8/a4);
  a0=(a0*a8);
  a8=(-a0);
  if (res[0]!=0) res[0][1]=a8;
  a8=(a1/a11);
  if (res[0]!=0) res[0][2]=a8;
  a6=log(a6);
  a6=(a6/a2);
  a8=9.9500000000000000e-001;
  a8=(a6+a8);
  if (res[0]!=0) res[0][3]=a8;
  a9=(a9/a11);
  if (res[0]!=0) res[0][4]=a9;
  a6=(a6/a2);
  a6=(a6*a1);
  a6=(-a6);
  if (res[0]!=0) res[0][5]=a6;
  a7=(a7*a10);
  a5=(a5*a7);
  a5=(-a5);
  if (res[0]!=0) res[0][6]=a5;
  a3=(-a3);
  if (res[0]!=0) res[0][7]=a3;
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_f_lT_vT(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jac_f_lT_vT_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_f_lT_vT_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_f_lT_vT_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jac_f_lT_vT_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_f_lT_vT_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jac_f_lT_vT_incref(void) {
}

CASADI_SYMBOL_EXPORT void jac_f_lT_vT_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jac_f_lT_vT_n_in(void) { return 12;}

CASADI_SYMBOL_EXPORT casadi_int jac_f_lT_vT_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real jac_f_lT_vT_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_f_lT_vT_name_in(casadi_int i){
  switch (i) {
    case 0: return "FTtilde";
    case 1: return "dFTtilde";
    case 2: return "lMo";
    case 3: return "lTs";
    case 4: return "alphao";
    case 5: return "vMmax";
    case 6: return "lMT";
    case 7: return "vMT";
    case 8: return "tendon_stiff";
    case 9: return "tendon_stiff_shift";
    case 10: return "out_lT";
    case 11: return "out_vT";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_f_lT_vT_name_out(casadi_int i){
  switch (i) {
    case 0: return "jac";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_f_lT_vT_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s1;
    case 11: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_f_lT_vT_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jac_f_lT_vT_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
